version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - bubble

networks:
  bubble:
    external: true
